(() => {
 'use strict';
 const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 function sessionId(){let id;try{id=sessionStorage.getItem('jwhite-presence-session-v1');}catch{}if(!UUID.test(id||'')){id=crypto.randomUUID();try{sessionStorage.setItem('jwhite-presence-session-v1',id);}catch{}}return id;}
 let me=null,session=sessionId(),pulseBusy=false,readBusy=false,unreadBusy=false,unreadCount=0,unreadGeneration=0,unreadController=null,sessionKnown=false;
 async function request(path,options={}) {const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15_000);try{const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...options,signal:controller.signal});const d=await r.json().catch(()=>null);if(!r.ok){const e=new Error(d?.error||'Please try again.');e.status=r.status;throw e;}if(!d)throw new Error('The server returned an unreadable response.');return d;}finally{clearTimeout(timer);}}
 function paint(node,value){node.classList.add('presence-badge');node.dataset.online=value===true?'true':value===false?'false':'unknown';node.textContent=value===true?'● Online Now!':value===false?'○ Offline':'Status unavailable';}
 function badge(id,online){const b=el('span','Checking status…','presence-badge');b.dataset.presenceId=id;if(online!==undefined)paint(b,online);return b;}
 async function pulse(state='active'){if(!me||pulseBusy)return;if(state==='active'&&document.visibilityState==='hidden')return;pulseBusy=true;try{await request('/api/member-presence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:session,state})});}catch(e){if(e.status===401||e.status===403)setUser(null);}finally{pulseBusy=false;}}
 function paintUnread(value){const count=Number.isSafeInteger(value)&&value>0?value:0;unreadCount=count;for(const link of document.querySelectorAll('[data-message-inbox]')){let badge=link.querySelector?.('.message-unread-badge');if(!badge){badge=el('span',null,'message-unread-badge');badge.setAttribute('aria-hidden','true');badge.hidden=true;link.append?.(badge);}badge.textContent=count>99?'99+':String(count);badge.hidden=count===0;if(count)link.setAttribute?.('aria-label',`Messages, ${count} new message${count===1?'':'s'}`);else link.removeAttribute?.('aria-label');}}
 function resetUnread(){unreadGeneration+=1;unreadController?.abort();unreadController=null;unreadBusy=false;paintUnread(0);}
 async function refreshUnread(){if(!me||unreadBusy||document.visibilityState==='hidden')return;const epoch=unreadGeneration,memberId=me.id,controller=new AbortController();unreadController=controller;unreadBusy=true;const timer=setTimeout(()=>controller.abort(),15_000);try{const response=await fetch('/api/member-messages/unread',{credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{Accept:'application/json'}});const data=await response.json().catch(()=>null);if(controller.signal.aborted||epoch!==unreadGeneration||me?.id!==memberId)return;if(response.status===401||response.status===403){setUser(null);return;}if(!response.ok||!data||data.user?.id!==memberId||!Number.isSafeInteger(data.unread_count)||data.unread_count<0)return;paintUnread(data.unread_count);}catch(error){if(error?.name!=='AbortError'&&epoch===unreadGeneration&&me?.id===memberId){/* Keep the last known count through a temporary connection problem. */}}finally{clearTimeout(timer);if(unreadController===controller){unreadController=null;unreadBusy=false;}}}
 /* ROOSTER is invite only, so the header has exactly two faces: an approved
    member sees their account, and everybody else sees the door. Both faces are
    decided in this one function from one state, which is what makes "My
    Account" and "Invite Code or Log In" impossible to show at the same time.

    The state is guessed from the last visit until /api/profile/me answers,
    which is only a few hundred milliseconds later. Guessing beats blanking the
    header: the mobile door is a full width row, so hiding it and putting it
    back would shove the page down on every visit. A wrong guess corrects
    itself on the same paint and can never produce the conflicting pair. */
 const HINT='roster-session-hint-v1';
 function rememberedSession(){try{return localStorage.getItem(HINT)==='member'?'member':'guest';}catch{return 'guest';}}
 function paintSession(){const state=me?'member':sessionKnown?'guest':rememberedSession();
  if(document.body)document.body.dataset.rosterSession=state;
  for(const link of document.querySelectorAll('.nav-join,.mobile-nav-join,[data-roster-join]'))link.hidden=state!=='guest';
  for(const link of document.querySelectorAll('[data-roster-account]'))link.hidden=state!=='member';
  if(sessionKnown)try{localStorage.setItem(HINT,state);}catch{}}
 function myProfile(){for(const link of document.querySelectorAll('[data-my-profile]'))link.href=me?.id?`/profile.html?id=${encodeURIComponent(me.id)}`:'/my-profile.html';
  for(const link of document.querySelectorAll('[data-my-photos]'))link.href=me?.id?(me.owner?'/photos.html':`/member-photos.html?id=${encodeURIComponent(me.id)}`):'/my-profile.html?view=photos';
  for(const link of document.querySelectorAll('[data-my-friends]'))link.href=me?.id&&!me.owner?`/profile.html?id=${encodeURIComponent(me.id)}#friend-space`:'/#jwhite-friend-space';}
 function finishProfileLogin(){const next=new URL(location.href).searchParams.get('open'),path=location.pathname.replace(/\.html$/,'');if(path==='/members'&&me?.id&&['profile','photos','songs'].includes(next))location.replace('/my-profile.html'+(next==='profile'?'':'?view='+next));}
 function setUser(next){const id=next?.id;if(!UUID.test(id||'')){if(me)void pulse('offline');me=null;resetUnread();myProfile();paintSession();return;}const normalized=id.toLowerCase();if(me?.id!==normalized)resetUnread();me={id:normalized,owner:next.verified_owner===true};myProfile();paintSession();finishProfileLogin();void pulse();void refreshUnread();}
 async function sessionCheck(){
  // 200 means signed in AND approved; 401 or 403 means this is not a member
  // yet. Only those three answers are worth acting on and worth remembering.
  // An outage or a dropped connection is not an answer, so it neither logs
  // anybody out of the header nor overwrites what the last visit established.
  try{const d=await request('/api/profile/me');setUser(d.profile);sessionKnown=true;}
  catch(e){if(e.status===401||e.status===403){setUser(null);sessionKnown=true;}}
  finally{paintSession();}}
 function profileReady(profile){const id=profile?.id;if(id!=='owner'&&!UUID.test(id||''))return;for(const node of document.querySelectorAll('[data-presence-id="profile"]'))node.dataset.presenceId=id;
  for(const link of document.querySelectorAll('[data-viewed-profile]'))link.href=`/profile.html?id=${encodeURIComponent(id)}#public-profile`;
  void refreshPresence();}
 function friendBadges(){for(const card of document.querySelectorAll('.profile-friend-card')){if(card.querySelector('[data-presence-id]'))continue;try{const url=new URL(card.href,location.origin);const id=url.pathname==='/profile.html'?url.searchParams.get('id'):url.pathname==='/'?'owner':null;if(id==='owner'||UUID.test(id||''))card.append(badge(id));}catch{}}}
 async function refreshPresence(){if(readBusy||document.visibilityState==='hidden')return;friendBadges();const nodes=[...document.querySelectorAll('[data-presence-id]')].filter(n=>n.dataset.presenceId==='owner'||UUID.test(n.dataset.presenceId||''));const ids=[...new Set(nodes.map(n=>n.dataset.presenceId))];if(!ids.length)return;readBusy=true;
  try{for(let i=0;i<ids.length;i+=40){const group=ids.slice(i,i+40);try{const d=await request('/api/member-presence?ids='+group.join(','));nodes.filter(n=>group.includes(n.dataset.presenceId)).forEach(n=>paint(n,typeof d.statuses?.[n.dataset.presenceId]==='boolean'?d.statuses[n.dataset.presenceId]:null));}catch{nodes.filter(n=>group.includes(n.dataset.presenceId)).forEach(n=>paint(n,null));}}}finally{readBusy=false;}}
 function profileUrl(member){return UUID.test(member?.id||'')?`/profile.html?id=${encodeURIComponent(member.id)}`:'/people.html';}
 function memberCard(member){const card=el('article',null,'discover-card');const url=profileUrl(member);
  const link=el('a',null,'discover-identity');link.href=url;const avatar=el('span',null,'discover-avatar');if(typeof member.photo_url==='string'&&/^\/(?:profile\.jpg|api\/profile-photo\/[a-f0-9]{64})$/.test(member.photo_url)){const img=el('img');img.src=member.photo_url;img.alt=member.name;img.loading='lazy';img.addEventListener('error',()=>{avatar.replaceChildren(el('span',(member.name||'M')[0]));});avatar.append(img);}else avatar.textContent=(member.name||'M')[0];link.append(avatar,el('strong',member.name));card.append(link,badge(member.id,member.online));
  const actions=el('div',null,'discover-actions');const links=[['View Profile',url]];const state=member.relationship||'none';
  if(state==='none')links.push(['Add to My Roster',url+'#friend-space']);
  else if(state==='incoming')links.push(['Review Request','/members.html#friend-requests']);
  else {const names={self:'Your profile',accepted:'Connected',outgoing:'Request sent',following:'Following',declined:'Request closed'};actions.append(el('span',names[state]||'Connection unavailable','discover-relationship'));}
  if(state!=='self')links.push(['Send Message',`/members.html?to=${encodeURIComponent(member.id)}#member-mail`]);
  for(const [label,href]of links){const a=el('a',label);a.href=href;actions.append(a);}card.append(actions);return card;}
 function setupDirectory(root,compact=false){const suggestions=!compact?window.RoosterConnections?.create(root):null;let seq=0,offset=0,next=null,loading=false,accessLocked=false;const status=el('p','Loading the roster…','community-status');status.setAttribute('role','status');const grid=el('div',null,'discover-grid');const form=el('form',null,'friend-search-form');form.setAttribute('role','search');const label=el('label','Search the roster by name');const input=el('input');input.type='search';input.maxLength=60;input.placeholder='Find someone…';input.id=compact?'quick-friend-search':'friend-search-input';label.htmlFor=input.id;const search=el('button','Search the Roster');search.type='submit';form.append(label,input,search);const more=el('button','Show More of the Roster');more.type='button';more.hidden=true;const refresh=el('button','Newest on the Roster');refresh.type='button';const gate=el('section',null,'directory-access-gate');gate.hidden=true;gate.setAttribute('aria-labelledby',input.id+'-gate-title');const eyebrow=el('span','APPROVED MEMBERS','directory-access-eyebrow');const gateTitle=el('h2','Open the ROOSTER directory');gateTitle.id=input.id+'-gate-title';const gateCopy=el('p','Member discovery stays inside the invite-only ROOSTER community. Log in with an approved account or request an invite to continue.');const gateActions=el('div',null,'directory-access-actions');const login=el('a','Log In');login.href='/members.html';const invite=el('a','Request an Invite');invite.href='/members.html#request-invite';gateActions.append(login,invite);gate.append(eyebrow,gateTitle,gateCopy,gateActions);
 root.append(form,refresh,status,gate,grid,more);if(compact){const all=el('a','View the Whole Roster »','view-all-members');all.href='/people.html';root.append(all);}
 function showAccessGate(){suggestions?.clear();accessLocked=true;form.hidden=true;grid.replaceChildren();more.hidden=true;gate.hidden=false;refresh.textContent='Check Access Again';status.textContent='The ROOSTER directory is available to approved members.';}
 function showDirectory(){accessLocked=false;form.hidden=false;gate.hidden=true;refresh.textContent='Newest on the Roster';}
 async function load(append=false){const epoch=++seq;loading=true;more.disabled=true;if(!append){offset=0;status.textContent='Loading the roster…';}try{const d=await request(`/api/members?q=${encodeURIComponent(input.value.trim())}&offset=${offset}&limit=${compact?8:24}`);if(epoch!==seq)return;showDirectory();const list=Array.isArray(d.members)?d.members.filter(m=>UUID.test(m.id||'')&&typeof m.name==='string'):[];if(!append)grid.replaceChildren();grid.append(...list.map(memberCard));suggestions?.update(d,list,{append,searching:Boolean(input.value.trim())});next=d.next_offset;more.hidden=compact||!Number.isSafeInteger(next);status.textContent=d.total?`${d.total.toLocaleString()} on the roster${input.value.trim()?' found':''}. Tap a name or picture to open their profile.`:'Nobody on the roster matches that. Try another name.';void refreshPresence();}catch(e){if(epoch!==seq)return;suggestions?.clear();if(e.status===401||e.status===403)showAccessGate();else{showDirectory();status.textContent='The ROOSTER directory is temporarily unavailable. Tap Newest on the Roster to try again.';}}finally{if(epoch===seq){loading=false;more.disabled=false;}}}
 form.addEventListener('submit',e=>{e.preventDefault();void load();});refresh.addEventListener('click',()=>{input.value='';void load();});more.addEventListener('click',()=>{if(!loading&&Number.isSafeInteger(next)){offset=next;void load(true);}});void load();
 if(!compact){if(new URL(location.href).searchParams.get('tab')==='search')input.focus();setInterval(()=>{if(!accessLocked&&!loading&&!input.value&&offset===0&&document.visibilityState!=='hidden')void load();},60_000);}
 }
 function setupMobileNavigation(){const menus=[...document.querySelectorAll('.mobile-nav-more,.nav-more')];if(!menus.length)return;
  for(const details of menus){const summary=details.querySelector('summary');details.addEventListener('keydown',event=>{if(event.key!=='Escape'||!details.open)return;event.preventDefault();details.open=false;summary?.focus();});details.addEventListener('click',event=>{if(event.target?.closest?.('a'))details.open=false;});}
  document.addEventListener('click',event=>{for(const details of menus)if(details.open&&!details.contains(event.target))details.open=false;});}
 function setupBookingTab(){for(const link of document.querySelectorAll('.nav-more-menu a,.mobile-nav-menu a')){if(link.textContent.trim().toLowerCase()!=='booking')continue;link.href='/booking';link.classList.add('nav-booking');link.textContent='Booking Marketplace';link.setAttribute('aria-label','Open the ROOSTER Booking marketplace');}}
 function setupProfileMusicNav(){for(const link of document.querySelectorAll('a[href="/radio.html#music-library"]')){link.href='/my-profile.html?view=songs';link.textContent='Profile Music';link.setAttribute('aria-label','Open your Profile Music');}for(const link of document.querySelectorAll('.nav-radio')){link.textContent='ORBIT';link.setAttribute('aria-label','Open ORBIT live radio');}}
 // The join count is always read from the live member directory, never written into the page.
 async function paintMemberTotal(){const nodes=[...document.querySelectorAll('[data-member-count]')];if(!nodes.length)return;
  try{const answer=await fetch('/api/members?limit=1&offset=0',{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}});
   if(!answer.ok)throw new Error('members');const data=await answer.json();
   if(!Number.isSafeInteger(data?.total)||data.total<0)throw new Error('total');
   for(const node of nodes){const value=node.querySelector('b');if(value)value.textContent=data.total.toLocaleString('en-US');node.setAttribute('data-member-count-ready','true');}
  }catch{for(const node of nodes)node.textContent='EVERYBODY CAN\u2019T BE ON THE ROOSTER.';}}
 function start(){setupBookingTab();setupProfileMusicNav();setupMobileNavigation();paintSession();paintUnread(0);void paintMemberTotal();const directory=document.querySelector('[data-member-directory]');if(directory)setupDirectory(directory);
  else if(document.querySelector('#public-profile, #jwhite-friend-space')){const panel=el('section',null,'discover-panel');panel.id='discover-friends';panel.append(el('h2','Build My Roster'),el('p','Meet the newest names on the ROOSTER. Send a request to add them to your roster.'));const anchor=document.querySelector('#jwhite-friend-space')||document.querySelector('.member-space-main');if(anchor){anchor.insertAdjacentElement('afterend',panel);setupDirectory(panel,true);}}
  window.JWhiteCommunity={setUser,refreshPresence,refreshMessages:refreshUnread};window.addEventListener('jwhite:profile-ready',e=>profileReady(e.detail));window.addEventListener('jwhite:messages-changed',event=>{const count=event.detail?.count;if(me&&Number.isSafeInteger(count)&&count>=0)paintUnread(count);else void refreshUnread();});if(window.JWhitePublicProfile)profileReady(window.JWhitePublicProfile);
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='hidden'){void sessionCheck();void refreshPresence();void refreshUnread();}else void pulse('offline');});
  window.addEventListener('pagehide',()=>{unreadController?.abort();if(me)void fetch('/api/member-presence',{method:'POST',credentials:'same-origin',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:session,state:'offline'})}).catch(()=>{});});
  setInterval(()=>{void pulse();void refreshPresence();},45_000);setInterval(()=>void refreshUnread(),20_000);void sessionCheck();void refreshPresence();
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
