(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s), create=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n};
const state={kind:null,trigger:null,scrollY:0,user:null,messages:[],selected:null,pendingPeer:null,controller:null,lastMona:null,timer:null};
const safeSession={get(k){try{return sessionStorage.getItem(k)}catch{return null}},set(k,v){try{sessionStorage.setItem(k,v)}catch{}}};
function uuid(){return crypto.randomUUID?crypto.randomUUID():'00000000-0000-4000-8000-'+Math.random().toString(16).slice(2).padEnd(12,'0').slice(0,12)}
function request(path,options={}){return fetch(path,{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},...options}).then(async r=>{const d=await r.json().catch(()=>({error:'The response could not be read.'}));if(!r.ok)throw Object.assign(new Error(d.error||'Please try again.'),{status:r.status});return d})}
const dock=create('div','roster-utility-dock');dock.setAttribute('aria-label','Inbox and MONA');
const inboxButton=create('button','', 'Inbox'),badge=create('span','roster-utility-badge');badge.hidden=true;inboxButton.append(badge);inboxButton.setAttribute('aria-expanded','false');
const monaButton=create('button','', 'MONA');monaButton.setAttribute('aria-expanded','false');dock.append(inboxButton,monaButton);document.body.append(dock);
function status(text,error=false){const n=$('.roster-utility-status');if(n){n.textContent=text||'';n.toggleAttribute('data-error',error)}}
function focusables(){return [...document.querySelectorAll('.roster-utility-panel button:not([disabled]),.roster-utility-panel textarea,.roster-utility-panel a[href]')].filter(n=>!n.hidden)}
function close(){if(!state.kind)return;const closing=state.kind;if(closing==='mona')saveMona(loadMona(),false);if(closing==='inbox')safeSession.set('roster-inbox-open','0');state.controller?.abort();clearInterval(state.timer);state.timer=null;const s=$('.roster-utility-scrim');state.kind=null;s?.removeAttribute('data-open');inboxButton.setAttribute('aria-expanded','false');monaButton.setAttribute('aria-expanded','false');setTimeout(()=>s?.remove(),matchMedia('(prefers-reduced-motion:reduce)').matches?0:180);scrollTo(0,state.scrollY);state.trigger?.focus({preventScroll:true})}
function shell(kind,trigger){close();state.kind=kind;state.trigger=trigger;state.scrollY=scrollY;const scrim=create('div','roster-utility-scrim');const panel=create('section','roster-utility-panel');panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label',kind==='inbox'?'Inbox':'MONA assistant');const head=create('header','roster-utility-head');const back=create('button','roster-utility-back','Back');back.hidden=true;const title=create('h2','',kind==='inbox'?'Inbox':'MONA');const x=create('button','roster-utility-close','Close');head.append(back,title,x);const body=create('div','roster-utility-body');body.append(create('p','roster-utility-status','Updating…'));panel.append(head,body);scrim.append(panel);document.body.append(scrim);requestAnimationFrame(()=>scrim.setAttribute('data-open',''));trigger.setAttribute('aria-expanded','true');trigger.setAttribute('aria-controls','roster-utility-panel');panel.id='roster-utility-panel';x.onclick=close;scrim.onpointerdown=e=>{if(e.target===scrim)close()};scrim.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const f=focusables();if(!f.length)return;const at=f.indexOf(document.activeElement);if(e.shiftKey&&at<=0){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&at===f.length-1){e.preventDefault();f[0].focus()}}};x.focus({preventScroll:true});return{body,back}}
function signedOut(body,message){body.replaceChildren();const gate=create('div','roster-signin');gate.append(create('p','',message||'Sign in to open your private Inbox.'));const a=create('a','','Sign in');a.href='/members.html#member-login';gate.append(a);body.append(gate)}
async function unread(){if(document.hidden)return;try{const d=await request('/api/member-messages/unread');const count=Math.max(0,Number(d.unread_count)||0);badge.textContent=count>99?'99+':String(count);badge.hidden=!count}catch(e){if(e.status===401)badge.hidden=true}}
function peer(m){return m.sender_id===state.user.id?{id:m.recipient_id,name:m.recipient_name}:{id:m.sender_id,name:m.sender_name}}
function threads(){const map=new Map;for(const m of state.messages){const p=peer(m);const row=map.get(p.id)||{...p,messages:[]};row.messages.push(m);map.set(p.id,row)}return [...map.values()].map(t=>({...t,messages:t.messages.sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at))})).sort((a,b)=>Date.parse(b.messages.at(-1).created_at)-Date.parse(a.messages.at(-1).created_at))}
function renderThread(body,id,back){const t=threads().find(x=>x.id===id);if(!t)return renderInbox(body,back);state.selected=id;safeSession.set('roster-inbox-thread',id);body.replaceChildren(create('p','roster-utility-status',''));back.hidden=false;back.onclick=()=>renderInbox(body,back);for(const m of t.messages){const n=create('article','roster-message',m.body||m.subject);if(m.sender_id===state.user.id)n.setAttribute('data-mine','');const time=create('time','',new Date(m.created_at).toLocaleString());n.append(time);body.append(n);if(m.recipient_id===state.user.id)request('/api/member-messages/read',{method:'POST',body:JSON.stringify({message_id:m.id})}).then(unread).catch(()=>{})}const form=create('form','roster-reply'),area=create('textarea');area.maxLength=3000;area.placeholder=`Reply to ${t.name||'member'}`;area.value=safeSession.get('roster-inbox-draft-'+id)||'';area.oninput=()=>safeSession.set('roster-inbox-draft-'+id,area.value);const send=create('button','roster-utility-action','Send reply');send.type='submit';const note=create('p','roster-utility-status','');form.append(area,send,note);form.onsubmit=async e=>{e.preventDefault();const text=area.value.trim();if(!text)return;send.disabled=true;note.textContent='Sending…';try{await request('/api/member-messages/send',{method:'POST',body:JSON.stringify({recipient_id:id,request_id:uuid(),subject:'Reply',body:text})});area.value='';safeSession.set('roster-inbox-draft-'+id,'');note.textContent='Sent.';await loadInbox(body,back,id)}catch(err){note.textContent=err.message+' Your draft is still here.';send.disabled=false}};body.append(form);area.focus({preventScroll:true})}
function renderInbox(body,back){body.replaceChildren(create('p','roster-utility-status','Updated just now'));back.hidden=true;const all=threads();if(!all.length)body.append(create('p','roster-signin','No conversations yet.'));for(const t of all){const b=create('button','roster-thread');b.type='button';b.append(create('strong','',t.name||'Member'),create('span','',t.messages.at(-1).body||t.messages.at(-1).subject));b.onclick=()=>renderThread(body,t.id,back);body.append(b)}}
async function loadInbox(body,back,openId){status('Updating…');try{const d=await request('/api/member-messages?directory=0');if(!d.user||!Array.isArray(d.inbox)||!Array.isArray(d.sent))throw new Error('Inbox returned an invalid response.');state.user=d.user;state.messages=[...d.inbox,...d.sent].filter((m,i,a)=>a.findIndex(x=>x.id===m.id)===i);const count=Number(d.unread_count)||0;badge.textContent=count>99?'99+':String(count);badge.hidden=!count;openId?renderThread(body,openId,back):renderInbox(body,back)}catch(e){if(e.status===401)return signedOut(body);status(e.message,true)}}
function openInbox(){const {body,back}=shell('inbox',inboxButton);safeSession.set('roster-inbox-open','1');void loadInbox(body,back,safeSession.get('roster-inbox-thread')).then(()=>{if(state.pendingPeer&&state.user&&!threads().some(t=>t.id===state.pendingPeer.id)){state.messages.push({id:'draft-'+state.pendingPeer.id,sender_id:state.user.id,recipient_id:state.pendingPeer.id,sender_name:state.user.name,recipient_name:state.pendingPeer.name,subject:'Start your message below.',body:'',created_at:new Date().toISOString()});renderThread(body,state.pendingPeer.id,back)}state.pendingPeer=null});state.timer=setInterval(()=>{if(!document.hidden)loadInbox(body,back,state.selected)},60000)}
function saveMona(log,open){safeSession.set('roster-mona-session',JSON.stringify({open,turns:log.slice(-8).map(x=>({role:x.role,text:x.text.slice(0,4000)}))}))}
function loadMona(){try{const v=JSON.parse(safeSession.get('roster-mona-session')||'{}');return Array.isArray(v.turns)?v.turns.slice(-8):[]}catch{return[]}}
function renderMonaTurn(log,node,turn){node.textContent=turn.text;node.dataset.role=turn.role;log.append(node)}
async function askMona(text,log,form,area,meta){state.controller?.abort();const controller=new AbortController;state.controller=controller;const user={role:'user',text},answer={role:'assistant',text:''};const turns=loadMona();turns.push(user,answer);renderMonaTurn(log,create('article','roster-mona-turn'),user);const output=create('article','roster-mona-turn roster-thinking','Searching and thinking');output.dataset.role='assistant';log.append(output);area.value='';const submit=$('button[type=submit]',form);submit.disabled=true;const controls=create('div','roster-mona-controls'),stop=create('button','','Stop');stop.type='button';stop.onclick=()=>controller.abort();controls.append(stop);form.before(controls);const timeout=setTimeout(()=>controller.abort(),28000);try{const response=await fetch('/api/mona/chat',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/x-ndjson'},body:JSON.stringify({message:text,history:turns.slice(-8,-2),surface:location.pathname,route:location.pathname+location.search+location.hash,live_room_key:document.body.dataset.liveRoomKey||null}),signal:controller.signal});if(!response.ok){const e=await response.json().catch(()=>({}));throw new Error(e.error||'MONA could not connect.')}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';output.textContent='';output.classList.remove('roster-thinking');for(;;){const {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array,{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==='delta'){answer.text+=event.text;output.textContent=answer.text}else if(event.type==='meta'){meta.textContent=`Updated just now · ${event.model||'live assistant'}`}else if(event.type==='fallback'){answer.text=event.text;output.textContent=answer.text}}if(done)break}if(!answer.text)throw new Error('MONA returned no answer.');saveMona(turns,false)}catch(e){answer.text=e.name==='AbortError'?'Stopped. Your message is ready to retry.':'Best move now\n1. Refresh your current workspace and try again. MONA’s live connection is unavailable; no action was taken.';output.textContent=answer.text;output.classList.remove('roster-thinking');const retry=create('button','','Retry');retry.type='button';retry.onclick=()=>{output.remove();controls.remove();askMona(text,log,form,area,meta)};controls.append(retry);saveMona(turns,false)}finally{clearTimeout(timeout);submit.disabled=false;stop.remove()}}
function openMona(){const {body}=shell('mona',monaButton);body.replaceChildren();const meta=create('p','roster-utility-status','Updating context…'),log=create('div','roster-mona-log');body.append(meta,log);for(const turn of loadMona())renderMonaTurn(log,create('article','roster-mona-turn'),turn);const form=create('form','roster-mona-form'),area=create('textarea');area.maxLength=1200;area.placeholder='What should we work on?';const submit=create('button','roster-utility-action','Ask MONA');submit.type='submit';form.append(area,submit);form.onsubmit=e=>{e.preventDefault();const text=area.value.trim();if(text)askMona(text,log,form,area,meta)};body.append(form);const refresh=()=>{if(document.hidden)return;request('/api/mona/context').then(d=>{meta.textContent='Updated just now';state.user=d.user}).catch(e=>{meta.textContent=e.status===401?'Sign in to use your private MONA context.':'Context refresh unavailable. MONA rechecks when you ask.'})};refresh();state.timer=setInterval(refresh,60000);saveMona(loadMona(),true);area.focus({preventScroll:true})}
inboxButton.onclick=openInbox;monaButton.onclick=openMona;document.addEventListener('visibilitychange',()=>{if(!document.hidden){unread();if(state.kind==='inbox')$('.roster-utility-status')?.replaceChildren(document.createTextNode('Refreshing…'))}});addEventListener('focus',unread);addEventListener('jwhite:session-changed',unread);unread();
document.addEventListener('click',event=>{const link=event.target.closest?.('a[href*="#member-mail"],[data-message-inbox],[data-profile-message-open]');if(!link||link.closest('.roster-utility-panel'))return;event.preventDefault();event.stopImmediatePropagation();try{const url=new URL(link.href,location.href),id=url.searchParams.get('to');if(id&&/^[a-f0-9-]{36}$/i.test(id)){state.pendingPeer={id:id.toLowerCase(),name:url.searchParams.get('name')||link.dataset.memberName||'Member'};safeSession.set('roster-inbox-thread',state.pendingPeer.id)}}catch{}openInbox()},true);
new MutationObserver(()=>document.querySelectorAll('.roster-guide-open,.roster-guide-dialog,nav [data-message-inbox],nav .nav-messages,nav .mobile-nav-messages,nav .nav-mona').forEach(node=>node.remove())).observe(document.body,{childList:true,subtree:true});
function openExplicitMona(){openMona();if(location.hash==='#mona')history.replaceState(history.state,'',location.pathname+location.search)}
addEventListener('hashchange',()=>{if(location.hash==='#mona')openExplicitMona()});
let restoredMona=false;try{restoredMona=JSON.parse(safeSession.get('roster-mona-session')||'{}').open===true}catch{}const legacyMona=location.hash==='#mona';if(legacyMona)setTimeout(openExplicitMona,0);else if(location.pathname.replace(/\.html$/,'')==='/members'&&location.hash==='#member-mail'||safeSession.get('roster-inbox-open')==='1')setTimeout(openInbox,0);else if(restoredMona)setTimeout(openMona,0);
})();
