import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';
import {presenceWrite,presenceRead,onlineMembers,PRESENCE_TTL} from '../netlify/functions/_shared/member-presence.mts';
import {getMembers} from '../netlify/functions/_shared/member-directory.mts';
import {startAudioUpload,putAudioPart,readAudioUpload,AUDIO_UPLOAD_LIMIT,AUDIO_PART_BYTES} from '../netlify/functions/_shared/audio-transfers.mts';
import {MemberError} from '../netlify/functions/_shared/member-auth.mts';
const origin='https://jwhitedidit.net',alice={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',name:'Alice'},bob={id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',name:'Bob'},owner={id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',name:'J.White Did It'};
const get=p=>new Request(origin+p),post=(p,body)=>new Request(origin+p,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
function memory(){const data=new Map();return {data,async get(k){return structuredClone(data.get(k)??null);},async setJSON(k,v,o){if(o?.onlyIfNew&&data.has(k))return {modified:false};data.set(k,structuredClone(v));return{modified:true};},async set(k,v,o){if(o?.onlyIfNew&&data.has(k))return {modified:false};data.set(k,structuredClone(v));return{modified:true};},async delete(k){data.delete(k);},async *list({prefix}){yield{blobs:[...data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};}};}
test('presence is authenticated, server timed, and cannot be posted for someone else',async()=>{const s=memory(),now=Date.now();const r=await presenceWrite(post('/api/member-presence',{session_id:randomUUID(),state:'active',member_id:bob.id,seen_at:9999999999999}),s,async()=>alice,now);assert.equal(r.status,200);assert.deepEqual(await onlineMembers([alice.id,bob.id],s,now),{[alice.id]:true,[bob.id]:false});assert.equal((await presenceWrite(post('/api/member-presence',{}),s,async()=>{throw new MemberError(401,'Log in')})).status,401);});
test('offline expiry, multiple tabs and logout are handled without false presence',async()=>{const s=memory(),now=Date.now(),a=randomUUID(),b=randomUUID();for(const id of [a,b])await presenceWrite(post('/api/member-presence',{session_id:id,state:'active'}),s,async()=>alice,now);await presenceWrite(post('/api/member-presence',{session_id:a,state:'offline'}),s,async()=>alice,now);assert.equal((await onlineMembers([alice.id],s,now))[alice.id],true);assert.equal((await onlineMembers([alice.id],s,now+PRESENCE_TTL+1))[alice.id],false);await presenceWrite(post('/api/member-presence',{session_id:b,state:'offline'}),s,async()=>alice,now);assert.equal((await onlineMembers([alice.id],s,now))[alice.id],false);});
test('owner alias resolves to authenticated owner presence; public response has no last seen or emails',async()=>{const s=memory(),p=memory();p.data.set('owner-binding',owner);await presenceWrite(post('/api/member-presence',{session_id:randomUUID(),state:'active'}),s,async()=>owner);const r=await presenceRead(get('/api/member-presence?ids=owner,'+alice.id),s,p);const d=await r.json();assert.deepEqual(d.statuses,{owner:true,[alice.id]:false});assert(!JSON.stringify(d).includes('seen_at'));assert(!JSON.stringify(d).includes('@'));});
test('presence rejects bad JSON, oversized bodies, invalid targets and cross origin writes',async()=>{const s=memory(),p=memory();const foreign=post('/api/member-presence',{session_id:randomUUID(),state:'active'});foreign.headers.set('Origin','https://other.example');assert.equal((await presenceWrite(foreign,s,async()=>alice)).status,403);assert.equal((await presenceRead(get('/api/member-presence?ids=bad'),s,p)).status,400);assert.equal((await presenceWrite(post('/api/member-presence',{padding:'x'.repeat(300)}),s,async()=>alice)).status,413);assert.equal(s.data.size,0);});
test('member directory lists actual profiles newest first and searches public display names only',async()=>{const p=memory(),d=memory(),s=memory();p.data.set('public-members/'+alice.id,{...alice,joined_at:'2026-09-05T18:00:00Z',email:'secret@example.com'});p.data.set('public-members/'+bob.id,{...bob,joined_at:'2026-09-05T19:00:00Z'});let r=await getMembers(get('/api/members'),p,d,s);assert.equal(r.status,200);let v=await r.json();assert.equal(v.members[0].id,bob.id);assert.equal(v.total,2);assert(!JSON.stringify(v).includes('secret'));v=await(await getMembers(get('/api/members?q=ALI'),p,d,s)).json();assert.equal(v.members[0].name,'Alice');assert.equal(v.total,1);});
test('directory supports pagination and does not invent signup time for older accounts',async()=>{const p=memory(),d=memory(),s=memory();for(const m of [alice,bob,owner])p.data.set('public-members/'+m.id,m);const v=await(await getMembers(get('/api/members?limit=2'),p,d,s)).json();assert.equal(v.total,3);assert.equal(v.next_offset,2);assert.equal(v.members[0].joined_at,null);assert.equal((await getMembers(get('/api/members?offset=-1'),p,d,s)).status,400);});
test('new 100 MB cap is enforced by the upload server',async()=>{assert.equal(AUDIO_UPLOAD_LIMIT,100*1024*1024);const s=memory();const good=await startAudioUpload(post('/api/audio-uploads/start',{request_id:randomUUID(),kind:'profile',size:AUDIO_UPLOAD_LIMIT,name:'song.mp3'}),s,async()=>alice);assert.equal(good.status,200);assert.equal((await good.json()).parts,50);const bad=await startAudioUpload(post('/api/audio-uploads/start',{request_id:randomUUID(),kind:'profile',size:AUDIO_UPLOAD_LIMIT+1,name:'song.mp3'}),s,async()=>alice);assert.equal(bad.status,413);});
test('100 MB is transferred and reassembled exactly with no chunk exceeding 2 MB',async()=>{const s=memory(),id=randomUUID(),size=100*1024*1024;await startAudioUpload(post('/api/audio-uploads/start',{request_id:id,kind:'profile',size,name:'song.mp3'}),s,async()=>alice);for(let part=0;part<50;part++){const bytes=new Uint8Array(AUDIO_PART_BYTES).fill(part);const r=await putAudioPart(new Request(origin+`/api/audio-uploads/part?upload_id=${id}&part=${part}`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/octet-stream'},body:bytes}),s,async()=>alice);assert.equal(r.status,200);}const file=await readAudioUpload(s,alice.id,id,'profile');assert.equal(file.size,size);const last=new Uint8Array(await file.slice(size-AUDIO_PART_BYTES).arrayBuffer());assert.equal(last[0],49);assert.equal(last.at(-1),49);await assert.rejects(readAudioUpload(s,bob.id,id,'profile'));});
test('new deployment includes all community entry files and no hardcoded online badge',async()=>{const build=await readFile(new URL('../build.mjs',import.meta.url),'utf8');for(const f of ['people.html','community.js','community.css','emoji-picker.js'])assert(build.includes(f));const index=await readFile(new URL('../index.html',import.meta.url),'utf8');assert(index.includes('id="community-feed"'));assert(!index.includes('<span>Online Now!</span>'));const profile=await readFile(new URL('../profile.html',import.meta.url),'utf8');assert(profile.includes('data-viewed-profile>This Profile</a>'));assert(profile.includes('>Discover</a>'));});
test('phone library keeps resumable server repair while offering a bounded smaller copy',async()=>{const code=await readFile(new URL('../member-clips.js',import.meta.url),'utf8');assert(code.includes("input.removeAttribute('capture')"));assert(code.includes("if (pickerOpen) return"));assert(code.includes('sourceForConversion = ready'));assert(code.includes('maxBytes:4*1024*1024'));assert(code.includes('let the server prepare it'));assert(code.includes('transferClip'));assert(code.includes('waitForMediaJob'));const converter=await readFile(new URL('../phone-video.js',import.meta.url),'utf8');assert(!converter.includes('getUserMedia('));assert(!converter.includes('fetch('));assert(converter.includes('video.duration>30'));assert(converter.includes('bytes>outputLimit'));assert(converter.includes('outputLimit*8*.85/video.duration'));});
