import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import sharp from 'sharp';
import {addFriend,getFriendCount,getFriendRequests,respondToFriendRequest} from '../netlify/functions/_shared/friends.mts';
import {startVideoUpload,putVideoPart,readVideoUpload,VIDEO_PART_BYTES} from '../netlify/functions/_shared/video-transfers.mts';
import {submitClip,getClips,checkClip,getClipVideo} from '../netlify/functions/_shared/member-clips.mts';
import {validatePrivateMessageVideo} from '../netlify/functions/_shared/private-message-videos.mts';
import {VIDEO_MODERATION_POLICY_VERSION} from '../netlify/functions/_shared/video-moderation.mts';
import {getInteractions,postInteraction} from '../netlify/functions/_shared/wall-interactions.mts';
import {getAlbum,uploadAlbumPhoto,deleteAlbumPhoto,getAlbumPhoto,MAX_ALBUM_PHOTOS} from '../netlify/functions/_shared/member-albums.mts';
import {POLICY_VERSION} from '../netlify/functions/_shared/comment-moderation.mts';
import {MemberError} from '../netlify/functions/_shared/member-auth.mts';
const origin='https://jwhitedidit.net',alice={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',name:'Alice',isOwner:false},bob={id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',name:'Bob',isOwner:false},owner={id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',name:'J.White Did It',isOwner:true};
const get=p=>new Request(origin+p),post=(p,data)=>new Request(origin+p,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)});
function memory(){const records=new Map(),tags=new Map();let n=0;const clone=v=>structuredClone(v??null);const write=(k,v,o={})=>{if(o.onlyIfNew&&records.has(k)||o.onlyIfMatch!==undefined&&o.onlyIfMatch!==tags.get(k))return {modified:false};records.set(k,clone(v));tags.set(k,String(++n));return {modified:true};};return{records,get:async k=>clone(records.get(k)),getWithMetadata:async k=>records.has(k)?{data:clone(records.get(k)),etag:tags.get(k)}:null,set:async(k,v,o)=>write(k,v,o),setJSON:async(k,v,o)=>write(k,v,o),delete:async k=>records.delete(k),async*list({prefix}){const keys=[...records.keys()].filter(k=>k.startsWith(prefix));for(let i=0;i<keys.length;i+=8)yield{blobs:keys.slice(i,i+8).map(key=>({key}))};}};}
function setup(){const friends=memory(),profiles=memory();profiles.records.set('owner-binding',{id:owner.id});for(const m of [alice,bob,owner])profiles.records.set('public-members/'+m.id,m);return{friends,profiles};}
const count=async(s,id)=>(await getFriendCount(get('/api/friends?target_id='+id),s.friends,s.profiles)).json();
const send=async(s,from,to)=>(await addFriend(post('/api/friends/add?target_id='+to,{}),s.friends,async()=>from,s.profiles)).json();
const answer=(s,who,id,action='accept')=>respondToFriendRequest(post('/api/friend-requests/respond',{request_id:id,action}),s.friends,async()=>who,s.profiles);
const inbox=async(s,m)=>(await getFriendRequests(get('/api/friend-requests'),s.friends,async()=>m,s.profiles)).json();
test('signup records alone no longer create friendships, including JWhite',async()=>{const s=setup();assert.equal((await count(s,'owner')).count,0);assert.equal((await count(s,alice.id)).count,0);assert.equal(s.friends.records.size,0);});
test('a request is pending for recipient and excluded from both friend counts',async()=>{const s=setup(),r=await send(s,alice,bob.id);assert.equal(r.state,'outgoing');assert.equal(r.added,false);assert.equal((await count(s,alice.id)).count,0);assert.equal((await count(s,bob.id)).count,0);const i=await inbox(s,bob);assert.equal(i.incoming[0].member_id,alice.id);assert.equal(i.incoming[0].name,'Alice');assert.equal(i.incoming[0].id,r.request_id);});
test('only recipient accepts; acceptance creates reciprocal counted friendship once',async()=>{const s=setup(),r=await send(s,alice,bob.id);assert.equal((await answer(s,alice,r.request_id)).status,404);assert.equal((await answer(s,owner,r.request_id)).status,404);assert.equal((await answer(s,bob,r.request_id)).status,200);assert.equal((await answer(s,bob,r.request_id)).status,200);assert.equal((await count(s,alice.id)).count,1);assert.equal((await count(s,bob.id)).count,1);assert.equal((await inbox(s,bob)).incoming.length,0);});
test('reciprocal send never silently accepts and duplicate clicks create one request',async()=>{const s=setup();await Promise.all(Array.from({length:12},()=>send(s,alice,bob.id)));assert.equal((await inbox(s,bob)).incoming.length,1);assert.equal((await send(s,bob,alice.id)).state,'incoming');assert.equal((await count(s,bob.id)).count,0);});
test('decline stays out of both counts and cannot be overwritten by accept retry',async()=>{const s=setup(),r=await send(s,alice,bob.id);assert.equal((await answer(s,bob,r.request_id,'decline')).status,200);assert.equal((await answer(s,bob,r.request_id,'accept')).status,409);assert.equal((await count(s,bob.id)).count,0);});
test('JWhite requests also require recipient acceptance',async()=>{const s=setup(),r=await send(s,owner,alice.id);assert.equal((await count(s,'owner')).count,0);assert.equal((await inbox(s,alice)).incoming[0].member_id,'owner');await answer(s,alice,r.request_id);assert.equal((await count(s,'owner')).count,1);assert.equal((await count(s,alice.id)).friends[0].profile_url,'/#home');});
test('legacy one way adds become requests, not accepted consent or deleted data',async()=>{const s=setup();s.friends.records.set('target/owner/'+alice.id,{member_id:alice.id,member_name:alice.name,created_at:new Date().toISOString()});assert.equal((await count(s,'owner')).count,0);const pending=(await inbox(s,owner)).incoming[0];assert(pending.legacy);await answer(s,owner,pending.id);assert.equal((await count(s,'owner')).count,1);assert(s.friends.records.has('target/owner/'+alice.id));});
test('friend requests reject cross origin and unauthenticated writes',async()=>{const s=setup();const r=post('/api/friends/add?target_id='+bob.id,{});r.headers.set('Origin','https://other.example');assert.equal((await addFriend(r,s.friends,async()=>alice,s.profiles)).status,403);assert.equal((await addFriend(post('/api/friends/add?target_id='+bob.id,{}),s.friends,async()=>{throw new MemberError(401,'Log in')},s.profiles)).status,401);assert.equal(s.friends.records.size,0);});
// This fixture is a locally generated, valid H.264 clip with real video frames.
const large=await readFile(new URL('./fixtures/public-clip-large.mp4',import.meta.url));
const repaired=await readFile(new URL('./fixtures/short-clip.mp4',import.meta.url));
const exact=bytes=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength);
async function transfer(store,bytes=large,m=alice,name='phone.mov'){const id=randomUUID();const response=await startVideoUpload(post('/api/video-uploads/start',{request_id:id,kind:'clip',size:bytes.length,name}),store,async()=>m);assert.equal(response.status,200,await response.clone().text());const d=await response.json();for(let part=0;part<d.parts;part++){const req=new Request(origin+`/api/video-uploads/part?upload_id=${id}&part=${part}`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/octet-stream'},body:bytes.subarray(part*VIDEO_PART_BYTES,(part+1)*VIDEO_PART_BYTES)});const res=await putVideoPart(req,store,async()=>m);assert.equal(res.status,200,await res.clone().text());}return id;}
test('6 MB phone MOV selection transfers fully before the server repair result is validated',async()=>{assert(large.length>4*1024*1024);const transfers=memory(),clips=memory();const id=await transfer(transfers);const file=await readVideoUpload(transfers,alice.id,id,'clip');assert.equal(file.type,'video/quicktime');assert.equal(file.size,large.length);let sourceBytes=0;const prepareVideo=async bytes=>{sourceBytes=bytes.byteLength;return validatePrivateMessageVideo(exact(repaired),'video/mp4',{maxBytes:100*1024*1024});};const r=await submitClip(post('/api/clips',{upload_id:id,request_id:randomUUID(),caption:'My studio clip'}),clips,{resolveMember:async()=>alice,transfers,prepareVideo});assert.equal(r.status,202,await r.clone().text());assert.equal(sourceBytes,large.length);const saved=await r.json();assert.equal((await(await getClips(get('/api/clips?member='+alice.id),clips)).json()).clips.length,0);const verdict=await checkClip(post('/api/clips/check',{id:saved.id}),clips,{resolveMember:async()=>alice,moderateVideo:async()=>({status:'approved',reason:'safe_music_community',policy_version:VIDEO_MODERATION_POLICY_VERSION})});assert.equal(verdict.status,200,await verdict.clone().text());const profiles=memory();const played=await getClipVideo(get('/api/clip-video/'+saved.id),clips,profiles);assert.equal(played.status,200);assert.equal((await played.arrayBuffer()).byteLength,repaired.length);});
test('video chunks cannot be read by another member and sources above 100 MB are rejected',async()=>{const store=memory(),id=await transfer(store);await assert.rejects(readVideoUpload(store,bob.id,id,'clip'),e=>e.status===404);assert.equal((await startVideoUpload(post('/api/video-uploads/start',{request_id:randomUUID(),kind:'clip',size:100*1024*1024+1,name:'big.mp4'}),store,async()=>alice)).status,413);});
test('missing video chunks cannot finalize',async()=>{const store=memory(),id=randomUUID();await startVideoUpload(post('/api/video-uploads/start',{request_id:id,kind:'clip',size:large.length,name:'video.mp4'}),store,async()=>alice);await assert.rejects(readVideoUpload(store,alice.id,id,'clip'),e=>e.status===409);});
const mainComment='6a9bca7dc15e69bfede3d3ca';const iq=`?wall=owner&comment_id=${mainComment}`;function wallSetup(who=owner){return {store:memory(),deps:{main:memory(),walls:memory(),resolve:async()=>who,moderate:async()=>({status:'approved',policy_version:POLICY_VERSION,reason:'positive_or_respectful',checked_at:new Date().toISOString()})}};}
test('owner can react to comments on own wall; repeated taps do not inflate count',async()=>{const {store,deps}=wallSetup();for(let i=0;i<4;i++)assert.equal((await postInteraction(post('/api/wall-interactions/post'+iq,{action:'react',reaction:'apple',name:'Spoof'}),store,deps)).status,200);let d=await(await getInteractions(get('/api/wall-interactions'+iq),store,deps)).json();assert.equal(d.counts.apple,1);assert.equal(d.reaction,'apple');await postInteraction(post('/api/wall-interactions/post'+iq,{action:'react',reaction:null}),store,deps);d=await(await getInteractions(get('/api/wall-interactions'+iq),store,deps)).json();assert.equal(d.counts.apple,0);});
test('owner reply is server named, links back to owner, and retries do not duplicate it',async()=>{const {store,deps}=wallSetup(),body={action:'reply',message:'Appreciate you!',request_id:randomUUID(),name:'Somebody Else'};for(let i=0;i<2;i++)assert.equal((await postInteraction(post('/api/wall-interactions/post'+iq,body),store,deps)).status,200);const d=await(await getInteractions(get('/api/wall-interactions'+iq),store,deps)).json();assert.equal(d.replies.length,1);assert.equal(d.replies[0].name,'J.White Did It');assert.equal(d.replies[0].profile_url,'/#home');});
test('pending replies are hidden from visitors; deleted or nonexistent parents cannot be used',async()=>{const {store,deps}=wallSetup(alice);deps.moderate=async()=>({status:'pending',policy_version:POLICY_VERSION,checked_at:new Date().toISOString(),reason:'uncertain'});assert.equal((await postInteraction(post('/api/wall-interactions/post'+iq,{action:'reply',message:'Hello world',request_id:randomUUID()}),store,deps)).status,202);deps.resolve=async()=>{throw new MemberError(401,'Log in')};const d=await(await getInteractions(get('/api/wall-interactions'+iq),store,deps)).json();assert.equal(d.replies.length,0);assert.equal((await getInteractions(get('/api/wall-interactions?wall=owner&comment_id='+'f'.repeat(64)),store,deps)).status,404);});
async function photoRequest(color=0){const bytes=await sharp({create:{width:24,height:24,channels:3,background:{r:color,g:20,b:30}}}).jpeg().toBuffer();const f=new FormData();f.set('photo',new Blob([bytes],{type:'image/jpeg'}),'photo.jpg');return new Request(origin+'/api/member-album/upload',{method:'POST',headers:{Origin:origin},body:f});}
test('album accepts multiple sequential photos, deduplicates retries and serves sanitized pixels',async()=>{const store=memory();let first;for(const color of [10,50,90]){const r=await uploadAlbumPhoto(await photoRequest(color),store,async()=>alice);assert.equal(r.status,201,await r.clone().text());first=(await r.json()).photo;}assert.equal((await uploadAlbumPhoto(await photoRequest(90),store,async()=>alice)).status,200);const d=await(await getAlbum(get('/api/member-album?member='+alice.id),store)).json();assert.equal(d.photos.length,3);const image=await getAlbumPhoto(get(first.url),store);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/jpeg');});
test('album deletions require owning account and cannot remove another user photos',async()=>{const store=memory(),r=await uploadAlbumPhoto(await photoRequest(12),store,async()=>alice),p=(await r.json()).photo;await deleteAlbumPhoto(post('/api/member-album/delete?photo_id='+p.id,{}),store,async()=>bob);assert.equal((await getAlbumPhoto(get(p.url),store)).status,200);await deleteAlbumPhoto(post('/api/member-album/delete?photo_id='+p.id,{}),store,async()=>alice);assert.equal((await getAlbumPhoto(get(p.url),store)).status,404);});
test('album quota refuses extra uploads without persisting excess image bytes',async()=>{const store=memory();for(let i=0;i<MAX_ALBUM_PHOTOS;i++)store.records.set(`slots/${alice.id}/${i}`,{member_id:alice.id,slot:i,id:i.toString(16).padStart(64,'0'),created_at:new Date().toISOString()});const before=store.records.size;const r=await uploadAlbumPhoto(await photoRequest(111),store,async()=>alice);assert.equal(r.status,409);assert.equal(store.records.size,before);});
