import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import sharp from 'sharp';
import {getAlbum,uploadAlbumPhoto,updateAlbumCaption,deleteAlbumPhoto,purgeAlbumPhoto,getAlbumPhoto,MAX_ALBUM_PHOTOS,MAX_ALBUM_IMAGE_BYTES} from '../netlify/functions/_shared/member-albums.mts';
import {MemberError} from '../netlify/functions/_shared/member-auth.mts';
const origin='https://jwhitedidit.net',alice={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',name:'Alice'},bob={id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',name:'Bob'};
function memory(){const data=new Map();return {data,async get(k){return structuredClone(data.get(k)??null);},async set(k,v,o){if(o?.onlyIfNew&&data.has(k))return {modified:false};data.set(k,structuredClone(v));return{modified:true};},async setJSON(k,v,o){if(o?.onlyIfNew&&data.has(k))return{modified:false};data.set(k,structuredClone(v));return{modified:true};},async delete(k){data.delete(k);},async*list({prefix}){yield{blobs:[...data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};}};}
const get=p=>new Request(origin+p),post=(p,b)=>new Request(origin+p,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(b)});
async function upload(store,text='At the studio 🎵',member=alice){const bytes=await sharp({create:{width:24,height:24,channels:3,background:'#44aa66'}}).jpeg().toBuffer();const f=new FormData();f.set('photo',new Blob([bytes],{type:'image/jpeg'}),'test.jpg');f.set('caption',text);const req=new Request(origin+'/api/member-album/upload',{method:'POST',headers:{Origin:origin},body:f});return uploadAlbumPhoto(req,store,async()=>member);}
function seed(s,n=10){for(let slot=0;slot<n;slot++)s.data.set(`slots/${alice.id}/${slot}`,{id:slot.toString(16).padStart(64,'0'),member_id:alice.id,slot,created_at:'2026-09-05T22:00:00Z',width:24,height:24});}
test('photo upload saves emoji caption and serves it in the same member public album',async()=>{const s=memory(),r=await upload(s);assert.equal(r.status,201);const p=(await r.json()).photo;assert.equal(p.caption,'At the studio 🎵');const d=await(await getAlbum(get('/api/member-album?member='+alice.id),s)).json();assert.equal(d.photos[0].caption,p.caption);assert.equal(d.total,1);assert.equal(d.limit,10);assert.equal((await getAlbumPhoto(get(p.url),s)).status,200);});
test('album storage keeps a large phone photo at 1200 pixels and no more than 800 KB',async()=>{const s=memory(),bytes=await sharp({create:{width:2000,height:1000,channels:3,background:'#805533'}}).jpeg({quality:95}).toBuffer(),form=new FormData();form.set('photo',new Blob([bytes],{type:'image/jpeg'}),'phone.jpg');const r=await uploadAlbumPhoto(new Request(origin+'/api/member-album/upload',{method:'POST',headers:{Origin:origin},body:form}),s,async()=>alice);assert.equal(r.status,201,await r.clone().text());const p=(await r.json()).photo,image=await getAlbumPhoto(get(p.url),s),saved=Buffer.from(await image.arrayBuffer()),metadata=await sharp(saved).metadata();assert(saved.byteLength<=MAX_ALBUM_IMAGE_BYTES);assert.equal(metadata.width,1200);assert.equal(metadata.height,600);});
test('saved photo caption can be edited or removed without replacing the image',async()=>{const s=memory(),p=(await(await upload(s)).json()).photo;const before=await(await getAlbumPhoto(get(p.url),s)).arrayBuffer();for(const caption of ['New caption 🍏','']){const r=await updateAlbumCaption(post('/api/member-album/caption',{photo_id:p.id,caption}),s,async()=>alice);assert.equal(r.status,200);assert.equal((await r.json()).photo.caption,caption);}const after=await(await getAlbumPhoto(get(p.url),s)).arrayBuffer();assert.deepEqual(new Uint8Array(after),new Uint8Array(before));});
test('caption edit cannot modify another member photos even with a spoofed member id',async()=>{const s=memory(),p=(await(await upload(s)).json()).photo;const r=await updateAlbumCaption(post('/api/member-album/caption',{photo_id:p.id,caption:'Changed',member_id:alice.id}),s,async()=>bob);assert.equal(r.status,404);const d=await(await getAlbum(get('/api/member-album?member='+alice.id),s)).json();assert.equal(d.photos[0].caption,'At the studio 🎵');});
test('caption validation rejects long text, control characters, missing auth and cross site writes',async()=>{const s=memory(),p=(await(await upload(s)).json()).photo;for(const caption of ['x'.repeat(501),'bad\u0000caption',{}])assert.equal((await updateAlbumCaption(post('/api/member-album/caption',{photo_id:p.id,caption}),s,async()=>alice)).status,400);const foreign=post('/api/member-album/caption',{photo_id:p.id,caption:'x'});foreign.headers.set('Origin','https://other.test');assert.equal((await updateAlbumCaption(foreign,s,async()=>alice)).status,403);assert.equal((await updateAlbumCaption(post('/api/member-album/caption',{}),s,async()=>{throw new MemberError(401,'Log in');})).status,401);});
test('ten-photo albums still paginate without dropping pictures',async()=>{const s=memory();seed(s,9);const added=await upload(s);assert.equal(added.status,201);assert.match((await added.json()).photo.url,/\/9\//);let offset=0,photos=[];do{const d=await(await getAlbum(get(`/api/member-album?member=${alice.id}&offset=${offset}&limit=4`),s)).json();assert.equal(d.total,10);photos.push(...d.photos);offset=d.next_offset;}while(offset!==null);assert.equal(new Set(photos.map(p=>p.id)).size,10);});
test('ten-photo capacity is enforced before extra binary data is stored',async()=>{assert.equal(MAX_ALBUM_PHOTOS,10);const s=memory();seed(s);const n=s.data.size;assert.equal((await upload(s)).status,409);assert.equal(s.data.size,n);});
test('legacy album records stay stored while only ten photos are shown',async()=>{const s=memory();seed(s,12);const d=await(await getAlbum(get('/api/member-album?member='+alice.id),s)).json();assert.equal(d.total,10);assert.equal(d.photos.length,10);assert.equal(s.data.size,12);assert.equal((await upload(s)).status,409);});
test('the tenth album slot serves correctly and out-of-range new slots fail',async()=>{const s=memory();seed(s,9);const p=(await(await upload(s)).json()).photo;assert.match(p.url,/\/9\//);assert.equal((await getAlbumPhoto(get(p.url),s)).status,200);assert.equal((await getAlbumPhoto(get(p.url.replace('/9/','/10/')),s)).status,404);});
test('upload retry keeps an edited caption, and deletion removes stored photo data',async()=>{const s=memory(),p=(await(await upload(s)).json()).photo;await updateAlbumCaption(post('/api/member-album/caption',{photo_id:p.id,caption:'Edited'}),s,async()=>alice);const duplicate=await(await upload(s,'Original retry')).json();assert.equal(duplicate.duplicate,true);assert.equal(duplicate.photo.caption,'Edited');const removed=await deleteAlbumPhoto(post('/api/member-album/delete?photo_id='+p.id,{}),s,async()=>alice);assert.equal(removed.status,200);assert((await removed.json()).undo_seconds>0);assert.equal((await getAlbumPhoto(get(p.url),s)).status,404);assert.equal((await updateAlbumCaption(post('/api/member-album/caption',{photo_id:p.id,caption:'Resurrect'}),s,async()=>alice)).status,404);assert.equal(s.data.has(`slots/${alice.id}/0`),false);
 // The picture itself waits behind a removal record so Undo can put it back,
 // then leaves storage once that short window has passed.
 const trash=`trash/${alice.id}/${p.id}`;assert.equal(s.data.has(trash),true);s.data.set(trash,{...s.data.get(trash),removed_at:'2026-09-05T22:00:00Z'});
 assert.equal(await purgeAlbumPhoto(s,alice.id,p.id),true);assert.equal(s.data.has(`images/${alice.id}/${p.id}`),false);assert.equal(s.data.has(`captions/${alice.id}/${p.id}`),false);assert.equal(s.data.has(trash),false);});
const tick=()=>new Promise(r=>setImmediate(r));
async function openMine(response,url='/my-profile.html'){const listeners={},nodes={'my-profile-status':{},'my-profile-retry':{addEventListener:(e,f)=>listeners[e]=f}},targets=[];const sandbox={URL,AbortController,setTimeout,clearTimeout,document:{getElementById:id=>nodes[id]},location:{href:origin+url,replace:v=>targets.push(v)},fetch:async()=>response};vm.runInNewContext(await readFile(new URL('../my-profile.js',import.meta.url),'utf8'),sandbox);await tick();await tick();return {targets,nodes,listeners};}
const ok=(profile,more={})=>({ok:true,status:200,json:async()=>({profile,...more})});
test('My Profile resolves authenticated account rather than a viewed member or JWhite',async()=>{const {targets}=await openMine(ok(alice));assert.deepEqual(targets,['/profile.html?id='+alice.id]);});
test('My Photos routes to authenticated member album and every owner profile uses the shared profile experience',async()=>{assert.deepEqual((await openMine(ok(bob),'/my-profile.html?view=photos')).targets,['/member-photos.html?id='+bob.id]);assert.deepEqual((await openMine(ok(alice,{can_edit_owner:true}))).targets,['/profile.html?id='+alice.id]);});
test('signed out My Profile sends to login with self destination; errors never fall back to JWhite',async()=>{assert.deepEqual((await openMine({ok:false,status:401})).targets,['/members.html?open=profile']);const failed=await openMine({ok:false,status:503});assert.deepEqual(failed.targets,[]);assert.equal(failed.nodes['my-profile-retry'].hidden,false);assert.match(failed.nodes['my-profile-status'].textContent,/could not load/);});
test('invalid identity response cannot redirect a member to a forged page',async()=>{const d=await openMine(ok({id:'https://other.test/',name:'Wrong'}));assert.deepEqual(d.targets,[]);});
test('profile, member directory, ten-photo captions, emoji UI and album routes stay in the shipped source',async()=>{const file=async n=>readFile(new URL('../'+n,import.meta.url),'utf8');const profile=await file('profile.html');assert(profile.includes('data-view-photos>View My Photos'));assert(profile.includes('data-viewed-profile>This Profile'));assert.match(profile,/data-profile-tab="posts"[^>]*>Posts<\/button>/);assert(!/<a href="\/#home">Profile<\/a>/.test(profile));const home=await file('index.html');assert(home.includes('Search ROOSTER'));assert(/data-my-profile\b/.test(home)&&home.includes('href="/my-profile.html"'));const build=await file('build.mjs');for(const n of ['member-photos.html','my-profile.html','my-profile.js','community.js','emoji-picker.js','profile-album.js','photo-catalog.json'])assert(build.includes(n));const profileAlbum=await file('profile-album.js');assert(profileAlbum.includes("request('/photo-catalog.json')"));assert(profileAlbum.includes('member.verified_owner===true'));const album=await file('member-album.js');assert(album.includes('holds up to 10 photos'));const members=await file('members.html');assert(!(members.includes('<a href="/#home">Profile</a>')));});
